### ISSUE TITLE
训练好的模型

### ISSUE THREAD

**Issue by j201111100523** [Busa-yifan/smart-class-classroom#1]
非常好的工作，能否发一份训练好的模型?

**Comment by Busa-yifan** [comment]
你好，谢谢你的肯定。具体模型和实际应用场景关联很大，我们没有足够数据集做出可以泛化大部分场景的模型，所以还是需要你去根据你要测试的场景收集数据集
















在 2021-07-19 14:23:54，"j201111100523" ***@***.***> 写道：

非常好的工作，能否发一份训练好的模型?
